// Generated by CoffeeScript 1.7.1
(function() {
  var dropFile, fileOver;

  dropFile = function(e) {
    var files, i, reader, _i, _ref;
    e.stopPropagation();
    e.preventDefault();
    files = e.dataTransfer.files;
    for (i = _i = 0, _ref = files.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      console.log(files[i]);
      reader = new FileReader();
      reader.onload = (function(file) {
        return function(e) {
          var elem;
          elem = document.createElement('span');
          elem.innerHTML = '<li>' + '<img class="fileImage" src="' + e.target.result + '">' + '<ul class="fileInfo">' + '<li class="fileName">' + file.name + '</li>' + '<li class="fileSize">' + file.size + '</li>' + '<li class="fileBase64">' + '<input type="text" class="copyText" value="' + e.target.result + '">' + '</li>' + '</ul>' + '</li>';
          document.getElementById('result').insertBefore(elem, null);
        };
      })(files[i]);
      reader.readAsDataURL(files[i]);
    }
  };

  fileOver = function(e) {
    e.stopPropagation();
    e.preventDefault();
    e.dataTransfer.dropEffect = 'copy';
  };

  window.addEventListener('drop', dropFile, false);

  window.addEventListener('dragover', fileOver, false);

}).call(this);

//# sourceMappingURL=index.map
